# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 407d58c58580cbaee6026e270afb87b38714b6e5f31d274550787760c99420c27daf11ccb891f82fe2165769d0adaa3c066553637f01db5eda5655db52133950

test:
  secret_key_base: b33ce16e77ec93422c9f139ff84ecce4aa7402b40549d949c16a38704e71627e9eb5d8495ee2ccb38b49db035af8318bcb28f82ca0c2e32409a0839abb45d615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
